### ISSUE TITLE
Documentation to Pep8 Guidelines

### ISSUE THREAD

**Issue by shwh2628** [mlevis1/uav-image-analysis#2]
@mlevis1  Fix the documentation in both the notebooks to Pep8 guidelines. Comments should be ' # Dhjghjfghfj ' format where there is a space after the hashtag and a capital letter following.

**Comment by mlevis1** [comment]
@shwh2628 Documentation updated to Pep8 guidelines.  Added additional comments and added capital letters and spaces.
