### ISSUE TITLE
Add documentation for SVM notebook

### ISSUE THREAD

**Issue by shwh2628** [mlevis1/uav-image-analysis#3]
@mlevis1 Add more documentation to this notebook. Where does the 0 and 1 indexes come in that are mentioned in the README ?  I see one line of results for as an array of 0s and 1s but not sure how that got there from the functions. Adding more documentation to the functions (like the CNN notebook) could be very helpful.

**Comment by mlevis1** [comment]
@shwh I have added additional information and classifications to the README for a total of 4 (0 - good, 1 - blacked out, 2 - saturated, 3 - blurry).  The classifications are indicated in the test-images.csv file under "Label".
